/*
This file contains all constants in the app.
*/

const C = {
	// ACTION TYPES
	AIM_AT: "AIM_AT",
	KILL_HERO: "KILL_HERO",
	RESET: "RESET",
	DUCK_DOWN: "DUCK_DOWN",
	STAND_UP: "STAND_UP",
	TWITCH_FINGER: "TWITCH_FINGER",
	MISS_SHOT: "MISS_SHOT",
	BLAST_CORPSE: "BLAST_CORPSE",

	// HERO STATUSES
	AIMING: "AIMING",
	DUCKING: "DUCKING",
	WAITING: "WAITING",
	DEAD: "DEAD"
};

export default C;